name: conectytrack-frontend
region: nyc
domains:
  - domain: ctrack.conecty.io
    type: PRIMARY
    certificate: LETS_ENCRYPT
services:
  - name: frontend
    github:
      repo: tu-usuario/tu-repo
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install && npm run build
    run_command: npm start
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_TIME
        type: SECRET
      - key: VITE_API_URL
        value: "http://164.92.116.107:8082"
        scope: RUN_TIME
        type: SECRET
      - key: NODE_ENV
        value: "production"
        scope: RUN_TIME
        type: SECRET

